### ISSUE TITLE
Lucretius reference

### ISSUE THREAD

**Issue by evanwill** [its-airborne/timelines-site#16]
First item in your historical timeline mentions looking for the reference (outside of twitter), 

Here is the same translation in Archive.org, with the passage highlighted, 
https://archive.org/details/lucretiusonnatur00lucriala/page/290/mode/2up?q=%22morbid+infection+of+the+air%22

or direct link to page, 
https://archive.org/details/lucretiusonnatur00lucriala/page/290/mode/2up

In other translations the wording is pretty different, since it is actually a poem in verse. e.g. 

https://archive.org/details/onthenatureof00lucruoft/page/n295/mode/2up
https://archive.org/details/lucretiusonthena00lucruoft/page/256/mode/2up
https://archive.org/details/lucretiusonnatu00lucr/page/294/mode/2up

**Comment by paul-hammant** [comment]
Thanks Evan.
